site_name: BraIn Lab
dev_addr: 127.0.0.1:8080
site_url: https://anp-scp.github.io/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    scheme: default
    primary: white
    accent: blue
  font:
    text: Fira Mono
    code: Fira Code
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
  custom_dir: docs/overrides

nav:
  - index.md
  - Publications:
    - publications/index.md
  - News:
    - news/index.md
  - team.md

markdown_extensions: 
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - search
  - blog:
      blog_dir: publications
      post_date_format: yyyy
      blog_toc: false
      post_readtime: false
      pagination: false
      archive: false
  - blog:
      blog_dir: news
      pagination: false
      archive: false

extra_css:
  - stylesheets/extra.css
  - stylesheets/carousel.css
  - stylesheets/team.css

extra_javascript:
  - javascripts/carousel.js
  
hooks:
  - recent_post_hook.py
